name: Release

on:
  push:
    branches: ["create-packages"]

env:
  BUILD_TYPE: Release
  GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
  PYTHONUTF8: 1

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  create_apt_package_windows:
    name: Create apt package for Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
        ref: 'create-packages'
    - run: git submodule update --init --recursive
    
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.13
    
    - uses: taiki-e/install-action@v2
    
    - name: Set up GCC
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    - run: |
        cd c/ && g++ -std=c++17 -o libusearch_c.dll lib.cpp -I. -I ../include/ -I ../fp16/include/ -I ../robin-map/include/ && cd ../
        cd golang && mv ../c/libusearch_c.dll libusearch_c.dll && go test -v

  create_apt_package_macOS:
    name: Create apt package for macOS
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
        ref: 'create-packages'
    - run: git submodule update --init --recursive

    - run: brew install gcc-12

    - run: |
        cd c/ && g++ -std=c++17 -o libusearch_c.dll lib.cpp -I. -I ../include/ -I ../fp16/include/ -I ../robin-map/include/ && cd ../
        cd golang && mv ../c/libusearch_c.dll libusearch_c.dll && go test -v

