name: Release

on:
  push:
    branches: ["create-packages"]

env:
  BUILD_TYPE: Release
  GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
  PYTHONUTF8: 1

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  create_apt_packages_macOS:
    name: Create brew package for macOS
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
        ref: 'create-packages'

    # - name: Install LLVM and Clang
    #   uses: KyleMayes/install-llvm-action@v1
    #   with:
    #     version: "10.0"

    - name: Install Usearch lib
      run: |
        which ruby
        # gem install rubyzip
        # /usr/bin/ruby usearch.rb